import { MenuListado } from '@core';
import { MenuItem } from './menu.model';

export const MENU: MenuListado[] = [
  {
    "id": 7,
    "title": "CATEGORIAS",
    "routerlink": null,
    "href": null,
    "icon": "cog",
    "target": null,
    "hassubmenu": false,
    "is_title": false,
    "parentid": 6,
    "parent": null,
    "orden": 1,
    "total": 0
  },
  {
    "id": 20,
    "title": "buscar",
    "routerlink": "/categoria/buscar",
    "href": null,
    "icon": "",
    "target": "",
    "hassubmenu": false,
    "is_title": false,
    "parentid": 7,
    "parent": "7",
    "orden": 1,
    "total": 0
  },
  {
    "id": 21,
    "title": "nuevo",
    "routerlink": "/categoria/nuevo",
    "href": null,
    "icon": "",
    "target": "",
    "hassubmenu": false,
    "is_title": false,
    "parentid": 7,
    "parent": "7",
    "orden": 1,
    "total": 0
  },
  {
    "id": 8,
    "title": "MARCAS",
    "routerlink": null,
    "href": null,
    "icon": "cog",
    "target": null,
    "hassubmenu": false,
    "is_title": false,
    "parentid": 6,
    "parent": null,
    "orden": 1,
    "total": 0
  },
  {
    "id": 22,
    "title": "buscar",
    "routerlink": "/marca/buscar",
    "href": null,
    "icon": "",
    "target": "",
    "hassubmenu": false,
    "is_title": false,
    "parentid": 8,
    "parent": "8",
    "orden": 1,
    "total": 0
  },
  {
    "id": 23,
    "title": "nuevo",
    "routerlink": "/marca/nuevo",
    "href": null,
    "icon": "",
    "target": "",
    "hassubmenu": false,
    "is_title": false,
    "parentid": 8,
    "parent": "8",
    "orden": 1,
    "total": 0
  },
  {
    "id": 9,
    "title": "PRODUCTOS",
    "routerlink": null,
    "href": null,
    "icon": "cog",
    "target": null,
    "hassubmenu": false,
    "is_title": false,
    "parentid": 6,
    "parent": null,
    "orden": 1,
    "total": 0
  },
  {
    "id": 24,
    "title": "buscar",
    "routerlink": "/producto/buscar",
    "href": null,
    "icon": "",
    "target": "",
    "hassubmenu": false,
    "is_title": false,
    "parentid": 9,
    "parent": "9",
    "orden": 1,
    "total": 0
  },
  {
    "id": 25,
    "title": "nuevo",
    "routerlink": "/producto/nuevo",
    "href": null,
    "icon": "",
    "target": "",
    "hassubmenu": false,
    "is_title": false,
    "parentid": 9,
    "parent": "9",
    "orden": 1,
    "total": 0
  },
  // {
  //   "id": 4,
  //   "title": "Area Trabajo",
  //   "routerlink": null,
  //   "href": null,
  //   "icon": null,
  //   "target": null,
  //   "hassubmenu": true,
  //   "is_title": true,
  //   "parentid": 0,
  //   "parent": null,
  //   "orden": 1,
  //   "total": 0
  // },
  {
    "id": 6,
    "title": "Almacen",
    "routerlink": null,
    "href": null,
    "icon": null,
    "target": null,
    "hassubmenu": true,
    "is_title": true,
    "parentid": 0,
    "parent": null,
    "orden": 2,
    "total": 0
  },
  {
    "id": 5,
    "title": "Seleccionar Área",
    "routerlink": "/area-trabajo/seleccionar",
    "href": null,
    "icon": "sitemap",
    "target": null,
    "hassubmenu": false,
    "is_title": false,
    "parentid": 4,
    "parent": null,
    "orden": 2,
    "total": 0
  },
  {
    "id": 8,
    "title": "F2 - ACPE",
    "routerlink": "/formulario-acpe/buscar",
    "href": null,
    "icon": "book-open",
    "target": null,
    "hassubmenu": false,
    "is_title": false,
    "parentid": 6,
    "parent": null,
    "orden": 3,
    "total": 0
  },
  {
    "id": 9,
    "title": "F3 - OPERACIONES",
    "routerlink": "/formulario-operaciones/buscar",
    "href": null,
    "icon": "book-content",
    "target": null,
    "hassubmenu": false,
    "is_title": false,
    "parentid": 6,
    "parent": null,
    "orden": 3,
    "total": 0
  },
  {
    "id": 10,
    "title": "F4 - FUNCIONAMIENTO",
    "routerlink": "/formulario-funcionamiento/buscar",
    "href": null,
    "icon": "book-open",
    "target": null,
    "hassubmenu": false,
    "is_title": false,
    "parentid": 6,
    "parent": null,
    "orden": 4,
    "total": 0
  }
];

